<?xml version="1.0"?>
<!DOCTYPE channel[
	<!ELEMENT channel (item+,title,link,image*,language?,description)>
	<!ATTLIST  channel version CDATA #REQUIRED>

	<!ELEMENT item (title?,link?,description?)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT link (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT image (title?|link?|url?)>
	<!ELEMENT url (#PCDATA)>
	<!ELEMENT language (#PCDATA)>	

	<!-- Internal System Notation Declaration -->
    <!NOTATION jpeg SYSTEM "image/jpeg">
    <!NOTATION png SYSTEM "image/png"> <!-- Corrected MIME type -->

    <!-- External (Public) Notation Declaration -->
    <!NOTATION gif PUBLIC "-//W3C//DTD GIF 1.0//EN" "http://www.w3.org/TR/gif.dtd">

    <!-- Entity using the notation declarations -->
    <!ENTITY imageJpeg SYSTEM "http://example.com/image.jpg" NDATA jpeg>
    <!ENTITY imagePng SYSTEM "http://example.com/image.png" NDATA png>
    <!ENTITY imageGif PUBLIC "-//W3C//GIF 1.0//EN" "http://example.com/image.gif" NDATA gif>

    <!-- General entity for the link of image -->
    <!ENTITY imageLink "http://example.com/image1.jpg">

    <!-- Parameterized entity for the word "title" -->
    <!ENTITY % titleEntity "title"> <!-- Parameterized entity used throughout the DTD -->
    
    <!-- Nested entity example -->
    <!ENTITY nestedEntity "This is a nested entity referring to &titleEntity;">
]>
<channel version="1.0">
    <item>
        <title>First Item Title</title>
        <link>http://example.com/first</link>
        <description>This is the first item description.</description>
    </item>
    <item>
        <link>http://example.com/second</link>
        <title>Second Item Title</title>
    </item>
    <item>
        <link>http://example.com/third</link>
        <description>This is the third item description without title.</description>
    </item>
    <title>Channel Title</title>
    <link>http://example.com/channel</link>
    <image>
        <url>&imageLink;</url> <!-- Using the general entity for image link -->
    </image>
    <language>English</language>
    <description>This is the channel description.</description>
</channel>	
