<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Course_Catalog [
    <!ELEMENT Chair (Professor)>
    <!ELEMENT Title (#PCDATA)>
    <!ELEMENT Course (Title, Description?, Instructors, Prerequisites?)>
    <!ATTLIST Course
        Number (CS106A | CS106B | CS107 | CS109 | CS124 | CS143 | CS145 | CS221 | CS228 | CS229 | EE108A | EE108B | LING180) #REQUIRED
        Enrollment (1070 | 110 | 130 | 180 | 280 | 320 | 500 | 60 | 620 | 90) #IMPLIED>
    <!ELEMENT Prereq (#PCDATA)>
    <!ELEMENT Lecturer (First_Name, Middle_Initial?, Last_Name)>
    <!ELEMENT Last_Name (#PCDATA)>
    <!ELEMENT Professor (First_Name, Middle_Initial?, Last_Name)>
    <!ELEMENT Department (Title, Chair, Course+)>
    <!ATTLIST Department Code (CS | EE | LING) #REQUIRED>
    <!ELEMENT First_Name (#PCDATA)>
    <!ELEMENT Description (#PCDATA)>
    <!ELEMENT Instructors ((Lecturer, Professor*) | (Professor+, Lecturer?))>
    <!ELEMENT Prerequisites (Prereq+)>
    <!ELEMENT Course_Catalog (Department+)>
    <!ELEMENT Middle_Initial (#PCDATA)>
]>
<Course_Catalog>
    <Department Code="CS">
        <Title>Software Engineering</Title>
        <Chair>
            <Professor>
                <First_Name>John</First_Name>
                <Middle_Initial>H</Middle_Initial>
                <Last_Name>Doe</Last_Name>
            </Professor>
        </Chair>
        <Course Number="CS109" Enrollment="1070">
            <Title>Introduction to Software Engineering</Title>
            <Description>Basic programming concepts.</Description>
            <Instructors>
                <Lecturer>
                    <First_Name>Alice</First_Name>
                    <Last_Name>Smith</Last_Name>
                </Lecturer>
                <Professor>
                    <First_Name>Robert</First_Name>
                    <Last_Name>Johnson</Last_Name>
                </Professor>
            </Instructors>
            <Prerequisites>
                <Prereq>CS106A</Prereq>
            </Prerequisites>
        </Course>
    </Department>
</Course_Catalog>
